### Trip select group activity
PUT http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7/select/3c6134e1-af1b-416a-a7b1-f82a86fa6dde
Content-Type: application/json

{}

### Trip predict
PUT http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7/predict
Content-Type: application/json

{}

### Tag get filtered
GET http://localhost:8080/tags/filter?keywords=n
Accept: application/json

### Tag get
GET http://localhost:8080/tags
Accept: application/json

### Participant delete Marius
DELETE http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7/participant/2c650ee0-b232-48fc-9751-91fb0080dccf
Accept: application/json

### Participant create Marius
POST http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7/participant
Content-Type: application/json

{
  "id": "2c650ee0-b232-48fc-9751-91fb0080dccf",
  "name": "Marius",
  "surname": "Stalder",
  "tags": [
    {
      "id": "ccff82da-d889-4b00-807b-cd61a0732aea",
      "name": "Sommer"
    },
    {
      "id": "e8ca6957-5fa3-4e0e-94c8-9c5c8c08650c",
      "name": "Graubünden"
    }
  ]
}

### Participant get Marius
GET http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7/participant/2c650ee0-b232-48fc-9751-91fb0080dccf
Accept: application/json

### Participant get Marcus
GET http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7/participant/8036bc87-7ca8-4aa0-9c38-d6dffbc360e5
Accept: application/json

### Trip get
GET http://localhost:8080/trip/4dfecd08-b91d-4002-b11a-ca8cf2f958f7
Accept: application/json

### Trip create
POST http://localhost:8080/trip
Content-Type: application/json

{
  "trip": {
    "id": "4dfecd08-b91d-4002-b11a-ca8cf2f958f7",
    "name": "Example Activity",
    "city": "Bern",
    "tripStatus": "pending",
    "date": "2022-06-02"
  },
  "initialParticipant": {
    "id": "8036bc87-7ca8-4aa0-9c38-d6dffbc360e5",
    "name": "Marcus",
    "surname": "May",
    "tags": [
      {
        "id": "ccff82da-d889-4b00-807b-cd61a0732aea",
        "name": "Sommer"
      }
    ]
  }
}
